### ISSUE TITLE
Use more than two rows in Holosphere parts lists if necessary

### ISSUE THREAD

**Issue by Gotolei** [mickelus/tetra#192]
## Feature Request

**Feature description**
In modpacks (Enigmatica 5 v0.5.2 in this case) there can be plenty of custom tool materials added. As it stands currently, the holosphere displays parts lists in two and only two rows, adding said materials onto them and eventually going off the side of the screen instead of wrapping around.
[This is a screenshot at 1080p on gui scale 3.](https://i.imgur.com/2ansgYZ.png) Goes right off the side of the screen. Some materials unseen.
[Scale 2.](https://i.imgur.com/HWuxeAX.png) Usable, all materials visible (but somewhat awkwardly unbalanced, if that's a concern).
In this case it's only one material that's off the side of the screen, but as the 1.12+ modding scene matures, it's possible that more might end up existing.

I'm imagining a few possible solutions to this:
- Automatically add rows as needed to wrap the holosphere based on number of materials
- Add a config for pack makers to define how many rows the holosphere uses
- Possibly also center-align parts lists

**How it improves the player experience**
In customized modpacks, users wouldn't need to lower GUI scale in order to see all materials.

**Tetra synergies**
Visual change only - makes Holosphere easier to use on more comfortable GUI levels.
This mod is generally seen as a modern replacement for Tinkers' and has become reasonably popular, and if PlusTIC et al. analogues end up existing (or even just pack-specific additions) then the ability to display lots of custom materials without issue would play well into that.

**Comment by mickelus** [comment]
Fixed in 3.0.0

**Comment by DefbeatCZ** [comment]
The problem seems to be still present on screen "Craft > Materials". Using Tetra 3.10, mods adding materials are create and botania. Running optifine.  Screen attached
![GUI Scale 2](https://user-images.githubusercontent.com/54858078/119193916-9dbf3200-ba82-11eb-8a85-7ba63a8c6eb3.png)
![GUI Scale 3](https://user-images.githubusercontent.com/54858078/119193928-a152b900-ba82-11eb-932d-266f140499d6.png)

**Comment by Gotolei** [comment]
A bit late but it's worth mentioning the parts list can be scrolled horizontally. There's no scrollbar or arrow or anything so you basically need to ask around or stumble upon it by accident, but it is indeed possible to get to the rest of the materials.

(Note that as a side effect, if you have a lot of materials and scroll in far enough, sometimes the materials list will appear empty for a few seconds when you open it after you've used it in the same session. Just let the animation play out, it always starts from the far left end.)
