### ISSUE TITLE
[Bug] erroneous advancement award due to data changes in vanilla.

### ISSUE THREAD

**Issue by esotericist** [mickelus/tetra#529]
### Observed behaviour

obtaining any item causes the intradimensional technology advancement to get awarded due to changes in the data json format, as discussed in https://github.com/Ellpeck/NaturesAura/issues/231

this also impacts 'mineral crackers', which gets awarded as soon as you right click with any item on any block

### Expected behaviour

certainly not this. i suspect based on other changes this probably would have been disabled, but you didn't think it necessary without the ability to obtain the item.

### Steps to reproduce

1. load up a minecraft world with tetra in it
2. obtain any item
3. observe 
![image](https://user-images.githubusercontent.com/1569754/147010135-79789865-a5dd-461b-a4d1-bbf52058df8f.png)

### Tetra version

4.1.0

### mGui version

no mgui present. mutil? 4.0.0

### Forge version

1.18.1-39.0.6

### Other mods

occurs with no other mods present, as this is due to a vanilla data change

**Comment by aWhisper20** [comment]
Thirded. Eating berries similarly meant I had cracked open a Geode.

**Comment by mickelus** [comment]
Fixed in 4.1.1.

**Comment by ellbristow** [comment]
I'm afraid it's not completely fixed. Eating Mushroom Stew still triggers "Mineral Crackers" in 4.1.1, mUtil version 4.0.0

**Comment by ellbristow** [comment]
Also tested in 4.1.2, same result

**Comment by mickelus** [comment]
Thank you for putting in the effort to test things out! The mineral crackers advancement will be fixed in the next release!
