### ISSUE TITLE
[Bug] Crash with Origins: Classes (Forge) 1.19.2

### ISSUE THREAD

**Issue by crafting-Aaron** [mickelus/tetra#735]
### Observed behaviour

A crash will occur when booting up the game once Tetra is updated to the latest version 5.3.1. If downgrading to the previous one of Tetra 5.3.0 there is no issue.

### Expected behaviour

For the game to properly boot up without any crash with both mods installed.

### Steps to reproduce

1. Update Tetra to current version 5.3.1
2. Have Origins: Classes (Forge) 1.2.0
3. Have Origins: Forge 1.19.2-1.7.1.0
4. Attempt to open the game (in this case, through curseforge app using Valhelsia 5 modpack)

### Crashlog

https://gist.github.com/crafting-Aaron/d3cb0ec29d9ea23f4a4152d95530fd76

### Tetra version

5.3.1

### mutil/mGui version

5.1.0

### Forge version

1.19.2 - 43.2.14

### Other mods

Very extensive list of mods. It is from the Valhelsia 5 Modpack + Create Addons such as Steam and Rails.  [https://gist.github.com/crafting-Aaron/179259272f8e6614d2fef9143700cf26](Modlist)

I have noticed in the crash log that Origins: Classes is the one being mentioned as the conflict.
> Invalid descriptor on origins_classes.mixins.json:common.tetra.WorkbenchTileMixin->@Inject::originsClasses$modifyResult.......

**Comment by crafting-Aaron** [comment]
Someone else is having the same problem with their report on the other mod [https://github.com/DragonsPlusMinecraft/origins-classes-forge/issues/29](Origins: Classes)

**Comment by CatAndPaste** [comment]
I have the same issue. Happens with 5.4.0 as well. I have a long list of mods, but the issue comes from new versions of Tetra not loading with Origins: Classes 1.2.0 installed.

Either disabling Origins: Classes or downgrading Tetra to 5.2.1 solves the problem.

Crash report (.jar files renamed for easier modpack manual updates): https://gist.github.com/CatAndPaste/6563d2e7cdf56ef21f4b3471ee966a04

**Comment by NovaLynxie** [comment]
Noticed the same behavior and disabling/removing Origins: Classes has worked for me. I'd prefer to be able to use Origins with Origins Classes so at least downgrading Tetra will help allow that to work till a patch fix is available.

**Comment by Wolframme** [comment]
I can confirm that in the latest Tetra update this issue persists.

**Comment by srimpsrimp** [comment]
also experiencing this bug

**Comment by schnoodly** [comment]
Also still having this issue with 5.5.1, and downgrading to 5.3.0 worked as above.
Would love to see the most recent updates fix this!
